<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [CheckingWorkMethodTestThrowsArithmExceptionTest]" guice-stage="DEVELOPMENT" verbose="0">
  <test thread-count="5" name="testExpectedArithmeticException(failed)" verbose="0">
    <classes>
      <class name="CheckingWorkMethodTestThrowsArithmExceptionTest">
        <methods>
          <include name="testExpectedArithmeticException" invocation-numbers="0 1"/>
        </methods>
      </class> <!-- CheckingWorkMethodTestThrowsArithmExceptionTest -->
    </classes>
  </test> <!-- testExpectedArithmeticException(failed) -->
</suite> <!-- Failed suite [CheckingWorkMethodTestThrowsArithmExceptionTest] -->
